version: "3.9"

services:
  api:
    container_name: api
    build: .
    ports:
      - 3001:3001
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - .:/app

  database:
    container_name: database
    image: postgres:latest
    ports:
      - 5431:5432
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U leticia -d miniblog"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
